"""add slug to Tag

Revision ID: 1d396e73d3f1
Revises: ffc923af4fe3
Create Date: 2026-04-13 15:17:29.300416

"""
# pyright: reportUnusedCallResult=false

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d396e73d3f1'
down_revision: str | Sequence[str] | None = 'ffc923af4fe3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(op.f('uq_tag_name'), 'tag', ['name'])
    op.create_unique_constraint(op.f('uq_tag_slug'), 'tag', ['slug'])
    op.create_unique_constraint(op.f('uq_tracked_item_slug'), 'tracked_item', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tracked_item_slug'), 'tracked_item', type_='unique')
    op.drop_constraint(op.f('uq_tag_slug'), 'tag', type_='unique')
    op.drop_constraint(op.f('uq_tag_name'), 'tag', type_='unique')
    op.drop_column('tag', 'slug')
    # ### end Alembic commands ###
