"""create all models

Revision ID: 4ca5a59e6c7c
Revises:
Create Date: 2026-04-13 15:30:17.662908

"""
# pyright: reportUnusedCallResult=false

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ca5a59e6c7c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('tracked_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracked_item')),
    sa.UniqueConstraint('slug', name=op.f('uq_tracked_item_slug'))
    )
    op.create_table('item_tag',
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_item_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_item.id'], name=op.f('fk_item_tag_tracked_item_id_tracked_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tracked_item_id', 'tag_id', name=op.f('pk_item_tag'))
    )
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_item.id'], name=op.f('fk_log_entry_tracked_item_id_tracked_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_entry'))
    )
    op.create_table('log_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('log_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entry.id'], name=op.f('fk_log_tag_log_entry_id_log_entry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_log_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'log_entry_id', name=op.f('pk_log_tag'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_tag')
    op.drop_table('log_entry')
    op.drop_table('item_tag')
    op.drop_table('tracked_item')
    op.drop_table('tag')
    # ### end Alembic commands ###
