"""add nullable '
slug' column

Revision ID: d0774f8030a9
Revises: 4ca5a59e6c7c
Create Date: 2026-04-13 15:41:19.746077

"""
# pyright: reportUnusedCallResult=false

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd0774f8030a9'
down_revision: str | Sequence[str] | None = '4ca5a59e6c7c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_tag_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tag_slug'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
