"""Add Tag,LogTag,ItemTag tables

Revision ID: ffc923af4fe3
Revises: 574ab9a0febc
Create Date: 2026-04-13 12:44:35.756668

"""
# pyright: reportUnusedCallResult=false

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ffc923af4fe3'
down_revision: str | Sequence[str] | None = '574ab9a0febc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_tag',
    sa.Column('tracked_item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_item_id'], ['tracked_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tracked_item_id', 'tag_id')
    )
    op.create_table('log_tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('log_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'log_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_tag')
    op.drop_table('item_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
