// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateLogEntryData, CreateLogEntryErrors, CreateLogEntryResponses, CreateTagData, CreateTagErrors, CreateTagResponses, CreateTrackedItemData, CreateTrackedItemErrors, CreateTrackedItemResponses, DeleteLogEntryData, DeleteLogEntryErrors, DeleteLogEntryResponses, DeleteTagData, DeleteTagErrors, DeleteTagResponses, DeleteTrackedItemData, DeleteTrackedItemErrors, DeleteTrackedItemResponses, GetLogEntryData, GetLogEntryErrors, GetLogEntryResponses, GetTagData, GetTagErrors, GetTagResponses, GetTrackedItemData, GetTrackedItemErrors, GetTrackedItemResponses, HealthCheckData, HealthCheckResponses, ListLogEntriesData, ListLogEntriesResponses, ListTagsData, ListTagsResponses, ListTrackedItemsData, ListTrackedItemsResponses, UpdateLogEntryData, UpdateLogEntryErrors, UpdateLogEntryResponses, UpdateTagData, UpdateTagErrors, UpdateTagResponses, UpdateTrackedItemData, UpdateTrackedItemErrors, UpdateTrackedItemResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List Tracked Items
 *
 * Endpoint to list all tracked items.
 */
export const listTrackedItems = <ThrowOnError extends boolean = false>(options?: Options<ListTrackedItemsData, ThrowOnError>) => (options?.client ?? client).get<ListTrackedItemsResponses, unknown, ThrowOnError>({ url: '/items', ...options });

/**
 * Create Tracked Item
 *
 * Endpoint to create a new tracked item.
 */
export const createTrackedItem = <ThrowOnError extends boolean = false>(options: Options<CreateTrackedItemData, ThrowOnError>) => (options.client ?? client).post<CreateTrackedItemResponses, CreateTrackedItemErrors, ThrowOnError>({
    url: '/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Tracked Item
 *
 * Endpoint to delete a tracked item by its slug.
 */
export const deleteTrackedItem = <ThrowOnError extends boolean = false>(options: Options<DeleteTrackedItemData, ThrowOnError>) => (options.client ?? client).delete<DeleteTrackedItemResponses, DeleteTrackedItemErrors, ThrowOnError>({ url: '/items/{slug}', ...options });

/**
 * Get Tracked Item
 *
 * Endpoint to get a tracked item by its slug.
 */
export const getTrackedItem = <ThrowOnError extends boolean = false>(options: Options<GetTrackedItemData, ThrowOnError>) => (options.client ?? client).get<GetTrackedItemResponses, GetTrackedItemErrors, ThrowOnError>({ url: '/items/{slug}', ...options });

/**
 * Update Tracked Item
 *
 * Endpoint to update an existing tracked item.
 */
export const updateTrackedItem = <ThrowOnError extends boolean = false>(options: Options<UpdateTrackedItemData, ThrowOnError>) => (options.client ?? client).patch<UpdateTrackedItemResponses, UpdateTrackedItemErrors, ThrowOnError>({
    url: '/items/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Log Entries
 *
 * Endpoint to list all log entries.
 */
export const listLogEntries = <ThrowOnError extends boolean = false>(options?: Options<ListLogEntriesData, ThrowOnError>) => (options?.client ?? client).get<ListLogEntriesResponses, unknown, ThrowOnError>({ url: '/entries', ...options });

/**
 * Create Log Entry
 *
 * Endpoint to create a new log entry.
 */
export const createLogEntry = <ThrowOnError extends boolean = false>(options: Options<CreateLogEntryData, ThrowOnError>) => (options.client ?? client).post<CreateLogEntryResponses, CreateLogEntryErrors, ThrowOnError>({
    url: '/entries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Log Entry
 *
 * Endpoint to delete a log entry.
 */
export const deleteLogEntry = <ThrowOnError extends boolean = false>(options: Options<DeleteLogEntryData, ThrowOnError>) => (options.client ?? client).delete<DeleteLogEntryResponses, DeleteLogEntryErrors, ThrowOnError>({ url: '/entries/{entry_id}', ...options });

/**
 * Get Log Entry
 *
 * Endpoint to get a log entry by ID, with optional extra data.
 */
export const getLogEntry = <ThrowOnError extends boolean = false>(options: Options<GetLogEntryData, ThrowOnError>) => (options.client ?? client).get<GetLogEntryResponses, GetLogEntryErrors, ThrowOnError>({ url: '/entries/{entry_id}', ...options });

/**
 * Update Log Entry
 *
 * Endpoint to update an existing log entry.
 */
export const updateLogEntry = <ThrowOnError extends boolean = false>(options: Options<UpdateLogEntryData, ThrowOnError>) => (options.client ?? client).patch<UpdateLogEntryResponses, UpdateLogEntryErrors, ThrowOnError>({
    url: '/entries/{entry_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Tags
 *
 * Endpoint to list all tags.
 */
export const listTags = <ThrowOnError extends boolean = false>(options?: Options<ListTagsData, ThrowOnError>) => (options?.client ?? client).get<ListTagsResponses, unknown, ThrowOnError>({ url: '/tags', ...options });

/**
 * Create Tag
 *
 * Endpoint to create a new tag.
 */
export const createTag = <ThrowOnError extends boolean = false>(options: Options<CreateTagData, ThrowOnError>) => (options.client ?? client).post<CreateTagResponses, CreateTagErrors, ThrowOnError>({
    url: '/tags',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Tag
 *
 * Endpoint to delete a tag by its slug.
 */
export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => (options.client ?? client).delete<DeleteTagResponses, DeleteTagErrors, ThrowOnError>({ url: '/tags/{slug}', ...options });

/**
 * Get Tag
 *
 * Endpoint to retrieve a tag by its slug.
 */
export const getTag = <ThrowOnError extends boolean = false>(options: Options<GetTagData, ThrowOnError>) => (options.client ?? client).get<GetTagResponses, GetTagErrors, ThrowOnError>({ url: '/tags/{slug}', ...options });

/**
 * Update Tag
 *
 * Endpoint to update an existing tag.
 */
export const updateTag = <ThrowOnError extends boolean = false>(options: Options<UpdateTagData, ThrowOnError>) => (options.client ?? client).patch<UpdateTagResponses, UpdateTagErrors, ThrowOnError>({
    url: '/tags/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
