// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BaseDetailResponse
 */
export type BaseDetailResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthCheckResponse
 */
export type HealthCheckResponse = {
    /**
     * Status
     */
    status: 'ok';
};

export type JsonDictInput = {
    [key: string]: JsonValueInput;
};

export type JsonDictOutput = {
    [key: string]: JsonValueOutput;
};

export type JsonValueInput = string | number | number | boolean | Array<JsonValueInput> | JsonDictInput | null;

export type JsonValueOutput = string | number | number | boolean | Array<JsonValueOutput> | JsonDictOutput | null;

/**
 * LogEntryCreateRequest
 */
export type LogEntryCreateRequest = {
    /**
     * Trackeditemid
     */
    trackedItemId: number;
    /**
     * Action
     */
    action: string;
    /**
     * Notes
     */
    notes?: string | null;
    details: JsonDictInput;
    /**
     * Performedat
     */
    performedAt?: string | null;
};

/**
 * LogEntryExtraResponse
 */
export type LogEntryExtraResponse = {
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    /**
     * Id
     */
    id: number;
    /**
     * Trackeditemid
     */
    trackedItemId: number;
    /**
     * Action
     */
    action: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Performedat
     */
    performedAt: string;
    details: JsonDictOutput;
    /**
     * Tags
     */
    tags?: Array<string>;
    trackedItem: TrackedItemResponse;
};

/**
 * LogEntryResponse
 */
export type LogEntryResponse = {
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    /**
     * Id
     */
    id: number;
    /**
     * Trackeditemid
     */
    trackedItemId: number;
    /**
     * Action
     */
    action: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Performedat
     */
    performedAt: string;
    details: JsonDictOutput;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * TagCreateRequest
 */
export type TagCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug?: string | null;
};

/**
 * TagResponse
 */
export type TagResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * TrackedItemCreateRequest
 */
export type TrackedItemCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    attributes: JsonDictInput;
    /**
     * Slug
     */
    slug?: string | null;
};

/**
 * TrackedItemResponse
 */
export type TrackedItemResponse = {
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    attributes: JsonDictOutput;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: HealthCheckResponse;
};

export type HealthCheckResponse2 = HealthCheckResponses[keyof HealthCheckResponses];

export type ListTrackedItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/items';
};

export type ListTrackedItemsResponses = {
    /**
     * Response Items-List Tracked Items
     *
     * Successful Response
     */
    200: Array<TrackedItemResponse>;
};

export type ListTrackedItemsResponse = ListTrackedItemsResponses[keyof ListTrackedItemsResponses];

export type CreateTrackedItemData = {
    body: TrackedItemCreateRequest;
    path?: never;
    query?: never;
    url: '/items';
};

export type CreateTrackedItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTrackedItemError = CreateTrackedItemErrors[keyof CreateTrackedItemErrors];

export type CreateTrackedItemResponses = {
    /**
     * Successful Response
     */
    200: TrackedItemResponse;
};

export type CreateTrackedItemResponse = CreateTrackedItemResponses[keyof CreateTrackedItemResponses];

export type DeleteTrackedItemData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/items/{slug}';
};

export type DeleteTrackedItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTrackedItemError = DeleteTrackedItemErrors[keyof DeleteTrackedItemErrors];

export type DeleteTrackedItemResponses = {
    /**
     * Successful Response
     */
    200: BaseDetailResponse;
};

export type DeleteTrackedItemResponse = DeleteTrackedItemResponses[keyof DeleteTrackedItemResponses];

export type GetTrackedItemData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/items/{slug}';
};

export type GetTrackedItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrackedItemError = GetTrackedItemErrors[keyof GetTrackedItemErrors];

export type GetTrackedItemResponses = {
    /**
     * Successful Response
     */
    200: TrackedItemResponse;
};

export type GetTrackedItemResponse = GetTrackedItemResponses[keyof GetTrackedItemResponses];

export type UpdateTrackedItemData = {
    body: TrackedItemCreateRequest;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: {
        /**
         * Update Slug
         */
        update_slug?: boolean;
    };
    url: '/items/{slug}';
};

export type UpdateTrackedItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTrackedItemError = UpdateTrackedItemErrors[keyof UpdateTrackedItemErrors];

export type UpdateTrackedItemResponses = {
    /**
     * Successful Response
     */
    200: TrackedItemResponse;
};

export type UpdateTrackedItemResponse = UpdateTrackedItemResponses[keyof UpdateTrackedItemResponses];

export type ListLogEntriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/entries';
};

export type ListLogEntriesResponses = {
    /**
     * Response Entries-List Log Entries
     *
     * Successful Response
     */
    200: Array<LogEntryResponse>;
};

export type ListLogEntriesResponse = ListLogEntriesResponses[keyof ListLogEntriesResponses];

export type CreateLogEntryData = {
    body: LogEntryCreateRequest;
    path?: never;
    query?: never;
    url: '/entries';
};

export type CreateLogEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLogEntryError = CreateLogEntryErrors[keyof CreateLogEntryErrors];

export type CreateLogEntryResponses = {
    /**
     * Successful Response
     */
    200: LogEntryResponse;
};

export type CreateLogEntryResponse = CreateLogEntryResponses[keyof CreateLogEntryResponses];

export type DeleteLogEntryData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: number;
    };
    query?: never;
    url: '/entries/{entry_id}';
};

export type DeleteLogEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLogEntryError = DeleteLogEntryErrors[keyof DeleteLogEntryErrors];

export type DeleteLogEntryResponses = {
    /**
     * Successful Response
     */
    200: BaseDetailResponse;
};

export type DeleteLogEntryResponse = DeleteLogEntryResponses[keyof DeleteLogEntryResponses];

export type GetLogEntryData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: number;
    };
    query?: {
        /**
         * Extra
         */
        extra?: Array<string> | null;
    };
    url: '/entries/{entry_id}';
};

export type GetLogEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLogEntryError = GetLogEntryErrors[keyof GetLogEntryErrors];

export type GetLogEntryResponses = {
    /**
     * Response Entries-Get Log Entry
     *
     * Successful Response
     */
    200: LogEntryResponse | LogEntryExtraResponse;
};

export type GetLogEntryResponse = GetLogEntryResponses[keyof GetLogEntryResponses];

export type UpdateLogEntryData = {
    body: LogEntryCreateRequest;
    path: {
        /**
         * Entry Id
         */
        entry_id: number;
    };
    query?: never;
    url: '/entries/{entry_id}';
};

export type UpdateLogEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLogEntryError = UpdateLogEntryErrors[keyof UpdateLogEntryErrors];

export type UpdateLogEntryResponses = {
    /**
     * Successful Response
     */
    200: LogEntryResponse;
};

export type UpdateLogEntryResponse = UpdateLogEntryResponses[keyof UpdateLogEntryResponses];

export type ListTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tags';
};

export type ListTagsResponses = {
    /**
     * Response Tags-List Tags
     *
     * Successful Response
     */
    200: Array<TagResponse>;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type CreateTagData = {
    body: TagCreateRequest;
    path?: never;
    query?: never;
    url: '/tags';
};

export type CreateTagErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTagError = CreateTagErrors[keyof CreateTagErrors];

export type CreateTagResponses = {
    /**
     * Successful Response
     */
    200: TagResponse;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/tags/{slug}';
};

export type DeleteTagErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
    /**
     * Successful Response
     */
    200: BaseDetailResponse;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type GetTagData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/tags/{slug}';
};

export type GetTagErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTagError = GetTagErrors[keyof GetTagErrors];

export type GetTagResponses = {
    /**
     * Successful Response
     */
    200: TagResponse;
};

export type GetTagResponse = GetTagResponses[keyof GetTagResponses];

export type UpdateTagData = {
    body: TagCreateRequest;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: {
        /**
         * Update Slug
         */
        update_slug?: boolean;
    };
    url: '/tags/{slug}';
};

export type UpdateTagErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTagError = UpdateTagErrors[keyof UpdateTagErrors];

export type UpdateTagResponses = {
    /**
     * Successful Response
     */
    200: TagResponse;
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];
